### ISSUE TITLE
Unable to load weights (Stage 2.1 PCAE Plug-in Training)

### ISSUE THREAD

**Issue by hibikaze-git** [ImKeTT/pcae#3] opened 2023-02-02 09:53 UTC
After Stage 1 BART VAE Finetuning, the following files were saved.
`./chackpoints/yelp/BART/best_val_vae_hidden.pt`

The following error occurred in Stage 2.1 PCAE Plug-in Training.
`RuntimeError: Error(s) in loading state_dict for VAE:
Missing key(s) in state_dict: "encoder.embed_tokens.weight", "encoder.embed_positions.weight", ...`

I thought that the key name "model." was the cause, so I rewrote the code below to remove "model.".
https://github.com/ImKeTT/pcae/blob/main/train.py#L234-L238

However, I got the following error:
`RuntimeError: Error(s) in loading state_dict for VAE:
Missing key(s) in state_dict: "pooler.dense.weight", "pooler.dense.bias", "z_linear.weight", "linear.weight".`

Please tell me how to fix it.

Thanks,

**Comment by ImKeTT** [comment] 2023-02-02 10:53
This is caused by the wrong vae saving command, please replace `model.state_dict()` with `vae.state_dict()` (as is corrected here https://github.com/ImKeTT/pcae/blob/main/train.py#L197). This error is probably cased by code transfer from my notebook, and thanks for pointing it out.

**Comment by hibikaze-git** [comment] 2023-02-02 13:56
Thank you for your correction.
"Stage 2.1 PCAE Plug-in Training" was completed.

However, the generated text seems to be a meaningless string as follows.
・Example of "./bart_result/pcae/sentences/yelp/sentiment/1-epoch10-bs5-lr0.0001-ln10-ns100-100K.txt"
`theitheiithetheithethethethethetheiiitheithethethethethethetheithetheithetheitheitheithethethethetheithethetheiiii ...`

**Comment by ImKeTT** [comment] 2023-02-02 15:39
The stage 1 log shows no sign of model convergence, which is different on my end. Anyway, I have uploaded my fine-tuned model weights, logs of the base VAE [here](https://drive.google.com/file/d/1hp_vm1rQIxWgCSkgm7cKtasGWxCG1kL8/view?usp=sharing) to aid the reproducibility. 

I have also rerun the fine-tuned process, and there are several glitches have been fixed. I believe u have taken care of some... if ur interested in the project and would like to improve it, u can always pull a request, I'll consider to merge it!

**Comment by hibikaze-git** [comment] 2023-02-03 03:32
thank you.
Using the weights you gave me, I confirmed that the correct sentences were generated.
The problem seems to be in "Stage 1 BART VAE Finetuning".
It looks like you copied the code from a notebook, would it be possible for you to share the original notebook?

**Comment by ImKeTT** [comment] 2023-02-03 11:45
Sorry, I don't have access to my original server and the notebook any more. I think current the Stage 1 BART VAE Finetuning should work now :)

**Comment by hibikaze-git** [comment] 2023-02-04 14:03
I cloned the latest version and ran "Stage 1 BART VAE Finetuning", but it seems that learning does not converge in my environment.
My environment may be the problem, so I would like to continue investigating.

**Comment by ImKeTT** [comment] 2023-03-08 02:52
Have you solved this problem yet? If yes, I will close this issue soon~ If no, plz don't hesitate to let me know what I can do to help~

**Comment by ImKeTT** [comment] 2023-03-11 02:53
Closing this issue since there's no further update from the author

**Closed as completed by ImKeTT** 2023-03-11 02:53 UTC
